---
title: "index"
author: "Bas"
date: '2022-05-09'
output: html_document
site: bookdown::bookdown_site
---

```{r}
bookdown::render_book(".")
```


<!--chapter:end:index.Rmd-->

---
title: "introduction"
output: html_document
date: '2022-05-07'
bibliography: My Library.bib
---

### Introductie

In ons project gaan we in op de erasmusladder, dit is een apparaat wat een muis over een aantal sensoren laat lopen. De ladder slaat het elke keer op als een muis over en sensor loopt. Hierdoor kan er gemeten worden wanneer een muis moeite heeft met lopen. Dit komt vaak door een fout in het cerrebelum.

### Bibliography

@cupidoDetectingCerebellarPhenotypes; @sathyanesanCerebellarContributionLocomotor2019; @vandervaartMotorDeficitsNeurofibromatosis2011; @vinuezavelozCerebellarControlGait2015 


<!--chapter:end:001_introduction.Rmd-->




<!--chapter:end:002_elegans.rmd-->


# Part 1

Placeholder


### Link naar artikel
### References
### Criteria artikel
### Overige data
### Extra's over artikel
### J: 
### K: 
### Opdracht L, M en N
### N: 
### O: 
### P:

<!--chapter:end:003_reprocubility.rmd-->




<!--chapter:end:004_CV.Rmd-->

---
title: "32_uur_plan"
output: html_document
date: '2022-05-06'
---

### Wat wil ik?

Ik zou later graag iets met next-generation sequencingen willen doen.
Het lijkt me dan leuk om een deel in het lab te staan maar ook een deel de data te verwerken.

### wat heb ik hiervoor nodig?

IK ben gaan zoeken naar vacatures die iets te maken hebben met NGS.
Vaak zie ik Python langs komen, dus ik wel me mischien verdiepen in Python maar ik weet het nog niet zeker.

<!--chapter:end:005_toekomst.Rmd-->

