---
title: "assignment 7"
author: "Bas"
date: '2022-05-17'
output: html_document
---

```{r}
library(dslabs)
library(readr)
library(tidyverse)
library(here)
library(DBI)
```

```{r}
# Laden van flu data en de eerste 10 rows skippen
flu_data <- read_csv(here("data","flu_data.csv"), skip = 10)

# Laden van denque data en de eerste 10 rows skippen
dengue_data <- read_csv(here("data","dengue_data.csv"), skip = 10)

# Laden van gampinder in gampinder (niet nuttig).
gapminder <- gapminder
```

```{r}
# Date alleen per jaar laten zien
#flu_data$Date <- format(flu_data$Date, "%Y")

# Date alleen per jaar laten zien
#dengue_data$Date <- format(dengue_data$Date, "%Y")

# gapminder zelfde colnaam geven
gapminder_tidy <- gapminder %>% rename(Date = year)
```

```{r}
# flu_data tidy maken
flu_data_tidy <- pivot_longer(data = flu_data, cols = -c("Date"), names_to = "country", values_to = "cases")

# en factor van country maken
flu_data_tidy$country <- as.factor(flu_data_tidy$country)

# dengue_data tidy maken
dengue_data_tidy <- pivot_longer(data = dengue_data, cols = -c("Date"), names_to = "country", values_to = "activity")

# en factor van country maken
dengue_data_tidy$country <- as.factor(dengue_data_tidy$country)
```

```{r}
# de duplicate rows verwijderen
flu_data_tidy <- unique(flu_data_tidy[,1:3])

# de duplicate rows verwijderen
dengue_data_tidy <- unique(dengue_data_tidy[,1:3])
```


```{r}
# Oplsaan als CSV bestand
write_csv(flu_data_tidy, path = here("data","flu_data_tidy.csv"))

# Oplsaan als CSV bestand
write_csv(dengue_data_tidy, path = here("data","dengue_data_tidy.csv"))

# Oplsaan als CSV bestand
write_csv(gapminder_tidy, path = here("data","gapminder_tidy.csv"))

# opslaan als rds bestand
write_rds(flu_data_tidy, path = here("data","flu_data_tidy.rds"))

# opslaan als rds bestand
write_rds(dengue_data_tidy, path = here("data","dengue_data_tidy.rds"))

# opslaan als rds bestand
write_rds(gapminder_tidy, path = here("data","gapminder_tidy.rds"))

view(flu_data_tidy)
view(gapminder_tidy)
```


```{sql, eval = FALSE}
# en table maken
CREATE TABLE flu_data (
  Date VARCHAR(50),
  country VARCHAR(50),
  cases VARCHAR(50),
  CONSTRAINT PK_flu PRIMARY KEY (Date,country)
);

# de date naar de table verplaatsen
COPY flu_data FROM 'C:/Users/Bas/Desktop/School/Programmeren/datascience/portfolio/data/flu_data_tidy.csv' WITH (FORMAT csv);

# de table laten zien
SELECT * FROM flu_data; 

# en table maken
CREATE TABLE dengue_data (
  Date VARCHAR(50),
  country VARCHAR(50),
  activity VARCHAR(50),
  CONSTRAINT PK_dengue PRIMARY KEY (Date,country)
);

# de date naar de table verplaatsen
COPY dengue_data FROM 'C:/Users/Bas/Desktop/School/Programmeren/datascience/portfolio/data/dengue_data_tidy.csv' WITH (FORMAT csv);

# de table laten zien
SELECT * FROM dengue_data; 
```

```{r}
# connect to the database
con <- dbConnect(RPostgres::Postgres(), 
                 dbname = "workflowsdb", 
                 host="localhost", 
                 port="5432", 
                 user="postgres", 
                 password="kaas") 

# laat de tables zien
dbListTables(con)

# laat de colummen in flu_data zien
dbListFields(con, "flu_data")

# laat het tabel flu_data zien
head(dbGetQuery(con, 'SELECT * FROM flu_data'))

# disconnect van de database
dbDisconnect(con) 
```

```{sql, eval = FALSE}
#create gapminder table
CREATE TABLE gapminder (
  country VARCHAR(50),
  Date VARCHAR(50),
  infant_mortality VARCHAR(50) not null,
  life_expectancy VARCHAR(50) not null,
  fertitlity VARCHAR(50) not null,
  population VARCHAR(50) not null,
  gdp VARCHAR(50) not null,
  continent VARCHAR(50),
  region VARCHAR(50),
  CONSTRAINT PK_gapminder PRIMARY KEY (Date,country)
);

#import the gampinder file
COPY gapminder FROM 'C:/Users/Bas/Desktop/School/Programmeren/datascience/portfolio/data/gapminder_tidy.csv' WITH (FORMAT csv);

# laat de tabel zien
SELECT * FROM gapminder; 
```

```{r}
# connect to the database
con <- dbConnect(RPostgres::Postgres(), 
                 dbname = "workflowsdb", 
                 host="localhost", 
                 port="5432", 
                 user="postgres", 
                 password="kaas") 

gapminder_flu <- dbGetQuery(con, 'SELECT *
FROM flu_data,gapminder
WHERE  flu_data.country = gapminder.country;'
)

# disconnect van de database
dbDisconnect(con) 

```

```{r}
# filter for the Netherlands and calculate the average cases over time
cases_netherlands <- gapminder_flu %>% filter(country == "Netherlands") %>% group_by(date=as.Date(date)) %>% summarise(mean_cases=mean(as.numeric(cases)))

# make a gg line plot
cases_netherlands %>%
  ggplot(aes(x = date, y = mean_cases)) +
  geom_line() +
  labs(
    title = "flu cases over time in the netherlands",
    y = "cases"
  )


```

